

services:

    web:
        platform: 'linux/amd64'
        build:
            context: ./
            dockerfile: ./docker/web/Dockerfile
        ports:
            - 80:80
        networks:
            - bnet
        volumes:
            - ./:/var/www/html/

    mysql:
        platform: 'linux/amd64'
        image: 'mysql:5.7'
        #image: 'mysql/mysql-server:5.7'  # todo: has troubles !!!
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        networks:
            - bnet
        volumes:
            - 'mysql:/var/lib/mysql/'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1


networks:
    bnet:
        driver: bridge


volumes:
    mysql:
        driver: local


