

version: '3'


services:

    web:
        #image: php:7.2-apache
        build: ./docker/web
        #build:
        #    context: ./docker/web
        #    dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - .:/var/www/html

    mysql:
        platform: 'linux/amd64'
        image: 'mysql:5.7'
        #image: 'mysql/mysql-server:5.7'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
#        volumes:
#            - 'mysql:/var/lib/mysql'
#
#
#volumes:
#    mysql:
#        driver: local

